export const EDUCATORS_CSV_DATA = [
    { "nome": "Adriana Bragotto", "especialidade": "Costura", "indicou": "Babi Rubira" },
    { "nome": "Alex Uzueli", "especialidade": "Marcenaria", "indicou": "Maria Lívia" },
    { "nome": "Ana Medeiros", "especialidade": "Dança", "indicou": "Danilo Alves" },
    { "nome": "André Montilha", "especialidade": "Marcenaria", "indicou": "Babi Rubira" },
    { "nome": "Andrea Peres", "especialidade": "Marcenaria", "indicou": "Babi Rubira" },
    { "nome": "Ariela", "especialidade": "Educação Alimentar", "indicou": "Luiz Camacho" },
    { "nome": "Babi Rubira", "especialidade": "Marcenaria", "indicou": "Maria Lívia" },
    { "nome": "Beca Chang", "especialidade": "Cerâmica", "indicou": "Andrea Peres" },
    { "nome": "Carlos Candido", "especialidade": "Drone Educativo", "indicou": "Gustavo Santos" },
    { "nome": "Carol Zanet", "especialidade": "Meditação e Mindfullness", "indicou": "Luiz Camacho" },
    { "nome": "Cesar Fabiano Lopes", "especialidade": "Circo", "indicou": "Silvinha Lopes" },
    { "nome": "Chico Maciel", "especialidade": "Marcenaria", "indicou": "Andrea Peres" },
    { "nome": "Claudia Bavagnoli", "especialidade": "Tapeçaria", "indicou": "Andrea Peres" },
    { "nome": "Cristiane Velasco", "especialidade": "Contação de Histórias", "indicou": "Maria Lívia" },
    { "nome": "Dani Storto", "especialidade": "Literatura", "indicou": "Luiz Camacho" },
    { "nome": "Danilo Alves", "especialidade": "Parkour", "indicou": "Luiz Camacho" },
    { "nome": "Edu Moreira", "especialidade": "Empreendedorismo", "indicou": "Maria Lívia" },
    { "nome": "Elisa Lunardi", "especialidade": "Cultura das Infâncias", "indicou": "Tati Garrido" },
    { "nome": "Everton França", "especialidade": "Criação de Jogos Digitais", "indicou": "Leonardo Galvão" },
    { "nome": "Felipe Almeida", "especialidade": "Panificação", "indicou": "Maria Lívia" },
    { "nome": "Felipe Corsini", "especialidade": "Marcenaria", "indicou": "Babi Rubira" },
    { "nome": "Flora Barcellos", "especialidade": "Dança", "indicou": "Dani Storto" },
    { "nome": "Fran Busico", "especialidade": "Meditação e Mindfullness", "indicou": "Luiz Camacho" },
    { "nome": "Giulliana Gardner", "especialidade": "Literatura", "indicou": "Everton França" },
    { "nome": "Guilherme Federighi", "especialidade": "Sustentabilidade", "indicou": "Rex" },
    { "nome": "Gustavo Santos", "especialidade": "Tecnologia", "indicou": "Maria Lívia" },
    { "nome": "Iris Carano", "especialidade": "Criação de Jogos Digitais", "indicou": "Leonardo Galvão" },
    { "nome": "João Venturini", "especialidade": "Xadrez", "indicou": "Túlio Vidal" },
    { "nome": "José Carlos", "especialidade": "Criação de Jogos Digitais", "indicou": "Leonardo Galvão" },
    { "nome": "Keli Rodrigues", "especialidade": "Criação de Jogos de Tabuleiro", "indicou": "Lucas Lorena" },
    { "nome": "Kristina Gonçalves", "especialidade": "Teatro", "indicou": "Edu Moreira" },
    { "nome": "Leo Oshiro", "especialidade": "Corpo e Movimento", "indicou": "Maria Lívia" },
    { "nome": "Leonardo Galvão", "especialidade": "Criação de Jogos Digitais", "indicou": "Lucas Lorena" },
    { "nome": "Livia Raizer", "especialidade": "Xadrez", "indicou": "João Venturini" },
    { "nome": "Lucas Lorena", "especialidade": "Criação de Jogos de Tabuleiro", "indicou": "Edu Moreira" },
    { "nome": "Luiz Camacho", "especialidade": "Pedagogia", "indicou": "Maria Lívia" },
    { "nome": "Marco Novais", "especialidade": "Marcenaria", "indicou": "Maria Lívia" },
    { "nome": "Marcos de Moraes", "especialidade": "Criação de Jogos Digitais", "indicou": "Lucas Lorena" },
    { "nome": "Maria Lívia", "especialidade": "Pedagogia", "indicou": "" },
    { "nome": "May", "especialidade": "Arte de rua", "indicou": "Livia Raizer" },
    { "nome": "Michelle Galindo", "especialidade": "Improvisação", "indicou": "Maria Lívia" },
    { "nome": "Michelle Zeitel", "especialidade": "Práticas Inclusivas", "indicou": "Lucas Lorena" },
    { "nome": "Rex", "especialidade": "Cidade Educadora", "indicou": "Luiz Camacho" },
    { "nome": "Samir", "especialidade": "Marcenaria", "indicou": "Babi Rubira" },
    { "nome": "Silvinha Lopes", "especialidade": "Dança", "indicou": "Luiz Camacho" },
    { "nome": "Tati Garrido", "especialidade": "Cultura das Infâncias", "indicou": "Maria Lívia" },
    { "nome": "Theo Grahl", "especialidade": "Fotografia", "indicou": "Babi Rubira" },
    { "nome": "Túlio Vidal", "especialidade": "Panificação", "indicou": "Edu Moreira" },
    { "nome": "Mateus", "especialidade": "Panificação", "indicou": "Everton França" },
    { "nome": "Beátriz Kovacsik", "especialidade": "Teatro", "indicou": "Babi Rubira" },
    { "nome": "Thiago Sgambato", "especialidade": "Teatro", "indicou": "Andrea Peres" },
    { "nome": "Laura", "especialidade": "Joalheria", "indicou": "Babi Rubira" },
    { "nome": "Ricardo Sylos", "especialidade": "Arquitetura", "indicou": "Andrea Peres" },
    { "nome": "Yuri Correa Piratello", "especialidade": "Jogos de tabuleiro", "indicou": "Lucas Lorena" },
    { "nome": "Ricardo Dadu", "especialidade": "Jogos de tabuleiro", "indicou": "Lucas Lorena" },
    { "nome": "Nanda Sales", "especialidade": "Jogos de Tabuleiro", "indicou": "Felipe" },
    { "nome": "Marco", "especialidade": "Jogos de Tabuleiro", "indicou": "Nanda Sales" },
    { "nome": "Claudia Rossi", "especialidade": "Tecnologias", "indicou": "Maria Lívia" },
    { "nome": "Julia Keneucke", "especialidade": "Dança", "indicou": "Marcos de Moraes" },
    { "nome": "Alex Pena", "especialidade": "Jogos de Tabuleiro", "indicou": "Lucas Lorena" },
    { "nome": "Lourdes Atié", "especialidade": "Sociologia", "indicou": "Maria Lívia" },
    { "nome": "Felipe", "especialidade": "Casa Cultural", "indicou": "Livia Raizer" },
    { "nome": "Lucimara", "especialidade": "", "indicou": "Mateus" },
    { "nome": "Renato", "especialidade": "", "indicou": "Mateus" },
    { "nome": "Deise", "especialidade": "", "indicou": "Mateus" },
    { "nome": "Luiz Paulo", "especialidade": "", "indicou": "Mateus" }
];
